[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs","@netlify/functions"]

[functions.environment]
  NODE_VERSION = "20"
