[build]
  publish = "."
  functions = "netlify/functions"

# Disabilita cache lato browser su endpoint JSON
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-store"
